numpy

In [5]:
import numpy as np

In [12]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
import math
math.sqrt(4)

2.0

In [6]:
c =np.array([[[1,2],[2,3],[3,4]]])

In [7]:
c

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [8]:
type(c)

numpy.ndarray

In [9]:
c.ndim

3

In [10]:
c.shape

(1, 3, 2)

In [13]:
c.size

6

# calculate the memory space took for c numpy array

In [18]:
c.dtype

dtype('int64')

In [19]:
c.itemsize*c.size

48

In [22]:
# get specific element
print("specified element is",c[0,1]) 

specified element is [2 3]


In [14]:
#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)
import numpy as np

#THE BASICS :

#initialize array

In [15]:
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [16]:

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [17]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


In [18]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


In [19]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [20]:

#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [21]:

#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [22]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [23]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [24]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [25]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [26]:
#change element
b[1,2]=8
print(b)


[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [27]:

b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

initializing different types of array

In [28]:
zm=np.zeros((3,4))

In [29]:
zm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
zm.ndim

2

In [31]:
zm.shape

(3, 4)

## all 1's matrix

In [32]:
ones=np.ones((4,4),dtype="int16")

In [33]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [34]:
ones[1,1]=100
ones.shape

(4, 4)

In [35]:
# any other matrix
np.full((4,5),100,dtype="float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [36]:
m100=np.full((4,5),100,dtype="float")
m100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

# reuse the already existing array and assign one value

In [37]:
np.full_like(m100,200,dtype="float")

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [39]:
np.random.random_sample((2,4))

array([[0.59728358, 0.8848827 , 0.2586783 , 0.37112574],
       [0.61935669, 0.94257859, 0.002462  , 0.09098567]])

In [40]:
np.random.rand(2,4)

array([[0.07346845, 0.6028897 , 0.16407556, 0.21285504],
       [0.59353271, 0.34303649, 0.3642478 , 0.83126742]])

In [58]:
np.random.randint(2,9,size=(3,3))

array([[7, 3, 7],
       [3, 6, 7],
       [6, 5, 7]], dtype=int32)